### ISSUE TITLE
Symptoms reliability

### ISSUE THREAD

**Issue by francocm** [Lobeslab-Ltd/covid-19-MT#2]
Opening an issue for this query as per instructions on main project `README.md`.

I want to explore in more depth the symptoms, however I noticed that a lot of them are empty in the CSV.

* Does empty mean 'No Symptoms'? On the other hand, you have the literal 'No Symptoms' on some of them.
* What is the underlying data-source used in generating that CSV? Manual based on the media update?
* Is there data available to show case random vs non-random swabs?

Thanks

**Comment by frankieinguanez** [comment]
Hi Franco.

- Empty means no information available.

- No symptoms would be listed if the person showed no symptoms

- The data-source is the daily briefings by Profs. Gauci. We watch them on a daily basis and update the data once the briefing ends. We also check the DOI documents. So manual media update.

- We do not have any data on the randomness of swabs.

Will be closing the issue. Thanks.
Frankie
